"""
Django settings for aivonx project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from .utils import _split_env_list, _ensure_http_scheme
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

if DEBUG:
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-32^!76^%94!5xdrzsu$ts$bhelz&j@gw&f*ikn6cekadkzawn&")
    ALLOWED_HOSTS = _split_env_list("DJANGO_ALLOWED_HOSTS", "*")
else:
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
    if not SECRET_KEY:
        raise ValueError("DJANGO_SECRET_KEY environment variable is required")
    ALLOWED_HOSTS = _split_env_list("DJANGO_ALLOWED_HOSTS")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = _ensure_http_scheme(_split_env_list("DJANGO_CORS_ALLOWED_ORIGINS"))
CSRF_TRUSTED_ORIGINS = _ensure_http_scheme(_split_env_list("DJANGO_CSRF_TRUSTED_ORIGINS"))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'proxy',
    'account',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Added for CORS
]

ROOT_URLCONF = 'aivonx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aivonx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant' # Traditional Chinese

TIME_ZONE = 'Asia/Taipei' # Taipei Time Zone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "PAGE_SIZE": 100, # List API 支援分頁時，每頁只傳回 100 筆
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination", # 分頁的參數是使用 limit 跟 offset
    "DEFAULT_AUTHENTICATION_CLASSES": ( # 驗證方式
        "rest_framework_simplejwt.authentication.JWTAuthentication", # JWT (access tokens)
        "rest_framework.authentication.SessionAuthentication", # Session
        "rest_framework.authentication.TokenAuthentication", # Token
    ),
    "DEFAULT_PERMISSION_CLASSES": ( # 權限要求
        "rest_framework.permissions.IsAuthenticated", # 必須要驗證過才能呼叫 API
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

APPEND_SLASH = False # 關閉自動補 / 功能，避免 API 呼叫錯誤

SPECTACULAR_SETTINGS = {
    'TITLE': 'aivonx proxy API',
    'DESCRIPTION': 'API documentation for aivonx proxy',
    'VERSION': '1.0.0',
}