### User Login
# @name account_login
POST {{baseUrl}}/api/account/login/
Content-Type: application/json

{
  "account": "root",
  "password": "changeme"
}

### Capture
@AccessToken = {{account_login.response.body.access}}
@RefreshToken = {{account_login.response.body.refresh}}

######################################

### Create Node
# @name node_create
POST {{baseUrl}}/api/proxy/nodes/
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Node 1",
  "address": "192.168.0.54",
  "port": 11434
}

### Expected Response
# Code: 201 Created
# {
#   "id": 1,
#   "name": "Node 1",
#   "address": "192.168.0.54",
#   "port": 11434,
#   "created_at": "yyyy-mm-ddThh:mm:ss+08:00"
# }

@NodeID = {{node_create.response.body.id}}

######################################
  
### Get Node Details
GET {{baseUrl}}/api/proxy/nodes/{{NodeID}}/
Authorization: Bearer {{AccessToken}}

### Expected Response
# Code: 200 OK
# {
#   "id": 1,
#   "name": "Node 1",
#   "address": "192.168.0.54",
#   "port": 11434,
#   "created_at": "yyyy-mm-ddThh:mm:ss+08:00"
# }

### List Nodes
# @name node_list
GET {{baseUrl}}/api/proxy/nodes/
Authorization: Bearer {{AccessToken}}

### Expected Response
# Code: 200 OK
# {
#   "count": 1,
#   "next": null,
#   "previous": null,
#   "results": [
#     {
#       "id": 1,
#       "name": "Node 1",
#       "address": "192.168.0.54",
#       "port": 11434,
#       "created_at": "yyyy-mm-ddThh:mm:ss+08:00"
#     }
#   ]
# }

######################################

### Update Node
# @name node_update
PUT {{baseUrl}}/api/proxy/nodes/{{NodeID}}/
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Node 1 Updated",
  "address": "192.168.0.54",
  "port": 11434
}

### Expected Response
# Code: 200 OK
# {
#   "id": 1,
#   "name": "Node 1 Updated",
#   "address": "192.168.0.54",
#   "port": 11434,
#   "created_at": "yyyy-mm-ddThh:mm:ss+08:00"
# }

######################################

### Delete Node
# @name node_delete
DELETE {{baseUrl}}/api/proxy/nodes/{{NodeID}}/
Authorization: Bearer {{AccessToken}}
### Expected Response
# Code: 204 No Content