### User Login
# @name account_login
POST {{baseUrl}}/api/account/login/
Content-Type: application/json

{
  "account": "root",
  "password": "changeme"
}

### Capture
@AccessToken = {{account_login.response.body.access}}
@RefreshToken = {{account_login.response.body.refresh}}

######################################

### Generate
POST {{baseUrl}}/api/proxy/call/
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "node_id": 1,
  "path": "/api/generate",
  "method": "POST",
  "body": {
    "model": "gpt-oss:20b",
    "prompt": "Hello!",
    "stream": false
  }
}