# Generated by Django 5.2.8 on 2025-12-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_node_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
