# Generated by Django 5.2.8 on 2025-12-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_node_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('least_active', 'Least active (default)'), ('lowest_latency', 'Lowest latency')], default='least_active', max_length=32)),
                ('weight', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy Config',
                'verbose_name_plural': 'Proxy Configs',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='available_models',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
