# Generated by Django 5.2.8 on 2025-12-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_proxyconfig_node_available_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='node_group',
        ),
    ]
