# Generated by Django 5.2.8 on 2025-12-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_delete_node_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyconfig',
            name='weight',
        ),
    ]
