# Generated by Django 5.2.8 on 2025-12-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0006_remove_proxyconfig_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
